### ISSUE TITLE
@actions/cache v4.0.4 import error

### ISSUE THREAD

**Issue by dsanders11** [actions/toolkit#2112]
**Describe the bug**

When importing `@actions/cache@v4.0.4` there's a "cannot find module" error for `@protobuf-ts/runtime-rpc`.

```
Unhandled error: Error: Cannot find module '@protobuf-ts/runtime-rpc'
Require stack:
- /home/runner/work/private-workflows/private-workflows/node_modules/@actions/cache/lib/generated/results/api/v1/cache.js
- /home/runner/work/private-workflows/private-workflows/node_modules/@actions/cache/lib/generated/results/api/v1/cache.twirp-client.js
- /home/runner/work/private-workflows/private-workflows/node_modules/@actions/cache/lib/internal/shared/cacheTwirpClient.js
- /home/runner/work/private-workflows/private-workflows/node_modules/@actions/cache/lib/cache.js
- /home/runner/work/_actions/actions/github-script/60a0d83039c74a4aee543508d2ffcb1c3799cdea/dist/index.js
```

**To Reproduce**
1. `yarn add @actions/cache@4.0.4`
2. `node -e 'require("@actions/cache")'`

**Expected behavior**

The package should be importable.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

This was likely broken in #2106 - there's a runtime dependency on `@protobuf-ts/runtime-rpc` (possibly other packages as well) which was broken when `@protobuf-ts/plugin` was moved to a dev dependency.

cc @Link-

**Comment by Link-** [comment]
Thanks for reporting this @dsanders11, testing didn't show this issue. I'll work on a patch.

**Comment by Link-** [comment]
Will be fixed in `4.0.5`
